"$schema" = "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json"
console_title_template = "{{ .Shell }} in {{ .Folder }}"
final_space = true
version = 2


# Left prompt
[[blocks]]
  alignment = "left"
  type = "prompt"

  # OS
  [[blocks.segments]]
    background = "#d3d7cf"
    foreground = "#000000"
    leading_diamond = "╭─"
    style = "diamond"
    template = " {{ if .WSL }}WSL at {{ end }}{{.Icon}}  "
    type = "os"

    [blocks.segments.properties]
      windows = "󰍲"
  # username
  [[blocks.segments]]
    background = "#d3d7cf"
    foreground = "#000000"
    style = "diamond"
    template = "{{ if .SSHSession }} {{ end }}{{ .UserName }} "
    type = 'session'

  # path
  [[blocks.segments]]
    background = "#123243"
    foreground = "#ffffff"
    powerline_symbol = ""
    style = "powerline"
    template = "   {{ path .Path .Location }} "
    type = "path"

    [blocks.segments.properties]
      home_icon = "~"
      style = "powerlevel"
      max_width = "70"

  # git status
  [[blocks.segments]]
    background = "#4e9a06"
    background_templates = [
    "{{ if or (.Working.Changed) (.Staging.Changed) }}#c4a000{{ end }}",
    "{{ if and (gt .Ahead 0) (gt .Behind 0) }}#f26d50{{ end }}",
    "{{ if gt .Ahead 0 }}#89d1dc{{ end }}",
    "{{ if gt .Behind 0 }}#4e9a06{{ end }}"
    ]
    foreground = "#000000"
    powerline_symbol = ""
    style = "powerline"
    template = " {{ .UpstreamIcon }}{{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }}{{ if gt .StashCount 0 }}  {{ .StashCount }}{{ end }} "
    type = "git"

    [blocks.segments.properties]
      branch_icon = " "
      fetch_stash_count = true
      fetch_status = true
      fetch_upstream_icon = true


# Right prompt
[[blocks]]
  alignment = "right"
  type = "prompt"

  # shell name
  [[blocks.segments]]
    background = "#123243"
    foreground = "#ffffff"
    type = 'shell'
    style = "diamond"
    leading_diamond = ""
    trailing_diamond = ""
    template = ' in <p:blue><b>{{ .Name }}</b></> '

  # time
  [[blocks.segments]]
    background = "#d3d7cf"
    foreground = "#000000"
    invert_powerline = true
    style = "diamond"
    template = " at <p:blue><b>{{ .CurrentDate | date .Format }}   "
    trailing_diamond = "─╮"
    type = "time"
  

# rpromt
[[blocks]]
  type = "rprompt"
  
  [[blocks.segments]]
    foreground = "#d3d7cf"
    style = "plain"
    template = " ─╯"
    type = "text"


# Left newLine prompt
[[blocks]]
  alignment = "left"
  newline = true
  type = "prompt"

  [[blocks.segments]]
    foreground = "#d3d7cf"
    foreground_templates = [ "{{ if gt .Code 0 }}#ef5350{{ end }}" ]
    style = "plain"
    template = "╰─❯"
    type = "text"


# Secondary prompt
[secondary_prompt]
  foreground = "#e0f8ff"
  foreground_templates = [ "{{ if gt .Code 0 }}#ef5350{{ end }}" ]
  template = '╰─❯❯ '


# Transient prompt
[transient_prompt]
  foreground = "#e0f8ff"
  foreground_templates = [ "{{ if gt .Code 0 }}#ef5350{{ end }}" ]
  template = " ─❯ "

